"""
Import all models here so Alembic's autogenerate can detect them.
Alembic compares Base.metadata against the DB — if a model isn't imported,
its table won't appear in autogenerated migrations.
"""

from app.models.ml_model import MLModel, ModelStatus
from app.models.prediction_log import PredictionLog
from app.models.user import User

__all__ = ["User", "MLModel", "ModelStatus", "PredictionLog"]
